
// Objective-C API for talking to the following Go packages
//
//	multicrypt
//	multicrypt/Neo/Transactions/ContractTransaction
//	multicrypt/Neo/RPC
//	multicrypt/Utils/Fixed8
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Hello_FRAMEWORK_H__
#define __Hello_FRAMEWORK_H__

#include "Hello.objc.h"
#include "ContractTransaction.objc.h"
#include "Rpc.objc.h"
#include "Util.objc.h"
#include "universe.objc.h"

#endif
